louvre_trp_homepage:
    path:     /
    defaults: { _controller: LouvreTrpBundle:Plateform:index }
	
louvre_trp_step1:
    path:    /step1
	defaults: { _controller: LouvreTrpBundle:Plateform:step1 }
